site_name: API Расписания raspyx2
site_url: https://tshoko1.github.io/raspyx2-docs/

theme:
  name: material

nav:
  - Главная: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search